import { type FlowLocale } from "@/lib/i18n/locales";
import type { PayrollAccuracyCheckKey } from "@/components/payroll-year-end/accuracy-evidence";

const yearEndCopyEn = {
  heroEyebrow: "FlowHR Admin",
  title: "Payroll Year-End and Withholding Receipt",
  description:
    "Preview annual settlement and issue employee withholding receipts with payroll compliance guards.",
  inputTitle: "Input",
  yearLabel: "Year",
  employeeIdLabel: "Employee number",
  nonTaxableAnnualIncomeLabel: "Non-taxable Annual Income",
  earnedIncomeTaxCreditLabel: "Earned Income Tax Credit",
  childTaxCreditLabel: "Child Tax Credit",
  additionalTaxCreditLabel: "Additional Tax Credit",
  annualIncomeTaxRateLabel: "Annual Income Tax Rate",
  localIncomeTaxRateLabel: "Local Income Tax Rate",
  issuerNameLabel: "Issuer Name",
  personalPensionLabel: "Personal Pension",
  insurancePremiumLabel: "Insurance Premium",
  medicalExpenseLabel: "Medical Expense",
  educationExpenseLabel: "Education Expense",
  donationLabel: "Donation",
  housingSavingsLabel: "Housing Savings",
  personalPensionEligibleLabel: "Personal Pension Eligible",
  insurancePremiumEligibleLabel: "Insurance Premium Eligible",
  medicalExpenseEligibleLabel: "Medical Expense Eligible",
  educationExpenseEligibleLabel: "Education Expense Eligible",
  donationEligibleLabel: "Donation Eligible",
  housingSavingsEligibleLabel: "Housing Savings Eligible",
  accessTokenLabel: "Connection token (optional)",
  bearerTokenPlaceholder: "Bearer token",
  actorIdFallbackLabel: "Admin account (dev fallback)",
  organizationIdFallbackLabel: "Organization (dev fallback)",
  previewSettlementAction: "Preview Settlement",
  recalculateSettlementAction: "Recalculate Settlement",
  loadInsuranceReconciliationAction: "Load Insurance Reconciliation",
  previewReceiptAction: "Preview Receipt",
  issueReceiptAction: "Issue Receipt",
  sessionErrorPrefix: "Session error",
  settlementTitle: "Settlement",
  noSettlementYet: "No settlement yet.",
  grossNetLabel: "Gross / Net",
  inputVectorHashLabel: "Input Basis Snapshot",
  taxCreditInputAppliedLabel: "Tax Credit Input / Applied",
  cappedTaxCreditsLabel: "Capped Tax Credits",
  taxCreditReasonCodesLabel: "Tax Credit Decision Summary",
  taxLiabilityLabel: "Tax Liability",
  priorWithheldLabel: "Prior Withheld",
  withholdingDeltaLabel: "Withholding Delta",
  additionalWithholdingDueLabel: "Additional Withholding Due",
  withholdingRefundLabel: "Withholding Refund",
  previewedRunsLabel: "Previewed Runs",
  recalculationTitle: "Recalculation",
  noRecalculationYet: "No recalculation yet.",
  incomeDeductionInputLabel: "Income Deduction Input",
  cappedDeductionLabel: "Capped Deduction",
  appliedDeductionLabel: "Applied Deduction",
  taxableIncomeLabel: "Taxable Income",
  cappedItemsLabel: "Capped Items",
  deductionReasonCodesLabel: "Deduction Decision Summary",
  deductionEligibilityLabel: "Deduction Eligibility",
  eligibilityBlockingReasonsLabel: "Eligibility Blocking Reasons",
  taxLiabilityDeltaLabel: "Tax Liability Delta",
  withholdingDeltaChangeLabel: "Withholding Delta Change",
  additionalDueLabel: "Additional Due",
  refundLabel: "Refund",
  insuranceReconciliationTitle: "Insurance Reconciliation",
  noInsuranceReconciliationReportYet: "No reconciliation report yet.",
  statusLabel: "Status",
  annualSocialInsuranceRunsLabel: "Annual Social Insurance (Runs)",
  comparedInsurancePremiumFinalizationLabel: "Compared Insurance Premium (Finalization)",
  deltaLabel: "Delta",
  finalizationHashLabel: "Finalization / Match Key",
  insuranceReasonCodeLabel: "Insurance Decision Summary",
  monthlyBreakdownLabel: "Monthly Breakdown",
  withholdingReceiptTitle: "Withholding Receipt",
  noReceiptSummaryYet: "No receipt summary yet.",
  receiptNumberLabel: "Receipt Number",
  canIssueIssuedLabel: "Can Issue / Issued",
  issuedAtLabel: "Issued At",
  pendingReceiptRunsLabel: "Pending Receipt Runs",
  blockingReasonsLabel: "Blocking Reasons",
  accuracyEvidenceTitle: "Calculation Accuracy Evidence",
  noAccuracyEvidenceYet: "Run settlement/recalculation/reconciliation to generate evidence.",
  accuracySummaryLabel: "Evidence Summary",
  accuracyPassLabel: "PASS",
  accuracyFailLabel: "FAIL",
  accuracyCheckLabels: {
    gross_net_balance: "Gross/Net balance",
    deduction_components_balance: "Deduction component balance",
    withholding_delta_balance: "Withholding delta balance",
    due_refund_exclusive: "Additional due/refund exclusivity",
    tax_credit_cap_balance: "Tax credit cap balance",
    taxable_income_deduction_balance: "Taxable income deduction balance",
    tax_liability_delta_balance: "Tax liability delta balance",
    withholding_delta_change_balance: "Withholding delta change balance",
    taxable_income_reduction_balance: "Taxable income reduction balance",
    settlement_recalculation_baseline_balance: "Settlement/recalculation baseline balance",
    insurance_reconciliation_status_balance: "Insurance reconciliation status balance",
    insurance_monthly_sum_balance: "Insurance monthly sum balance"
  } as Record<PayrollAccuracyCheckKey, string>,
  apiLogsTitle: "API Logs",
  apiLogsTotalLabel: "total",
  apiLogsSuccessLabel: "success",
  apiLogsFailLabel: "fail",
  apiLogsRunningLabel: "running",
  noApiCallYet: "No API call yet.",
  openPreflightChecklistAction: "Open Preflight Checklist",
  backToAdminAction: "Back to Admin",
  statusRequestFailed: "We couldn't complete the request. Review the current state and try again.",
  statusLoadedAnnualLiabilityPrefix: "loaded annual liability",
  statusRecalculatedTaxDeltaPrefix: "recalculated tax delta",
  statusLoadedInsuranceReconciliationPrefix: "loaded insurance reconciliation",
  statusDeltaLabel: "delta",
  statusIssuedPrefix: "issued",
  statusPreviewedPrefix: "previewed",
  statusInvalidInput: "Review the entered values and try again.",
  statusNonNegativeInteger: "must be a non-negative integer",
  statusRateBetweenZeroAndOne: "must be between 0 and 1",
  pendingSettlementPreview: "year-end settlement preview",
  pendingSettlementRecalculation: "year-end settlement recalculation",
  pendingReceiptIssue: "withholding receipt issue",
  pendingReceiptPreview: "withholding receipt preview",
  pendingInsuranceReconciliation: "year-end insurance reconciliation report",
  logPreviewSettlement: "preview year-end settlement",
  logRecalculateSettlement: "recalculate year-end settlement",
  logIssueReceipt: "issue withholding receipt",
  logPreviewReceipt: "preview withholding receipt",
  logInsuranceReconciliation: "year-end insurance reconciliation report",
  yesLabel: "YES",
  noLabel: "NO",
  okLabel: "OK",
  failLabel: "FAIL",
  capLabel: "cap",
  deductionItemLabels: {
    personalPensionKrw: "Personal Pension",
    insurancePremiumKrw: "Insurance Premium",
    medicalExpenseKrw: "Medical Expense",
    educationExpenseKrw: "Education Expense",
    donationKrw: "Donation",
    housingSavingsKrw: "Housing Savings"
  } as Record<string, string>,
  deductionEligibilityLabels: {
    personalPensionEligible: "Personal Pension",
    insurancePremiumEligible: "Insurance Premium",
    medicalExpenseEligible: "Medical Expense",
    educationExpenseEligible: "Education Expense",
    donationEligible: "Donation",
    housingSavingsEligible: "Housing Savings"
  } as Record<string, string>,
  taxCreditItemLabels: {
    earnedIncomeTaxCreditKrw: "Earned Income Credit",
    childTaxCreditKrw: "Child Credit",
    additionalTaxCreditKrw: "Additional Credit"
  } as Record<string, string>
};

export type PayrollYearEndCopy = typeof yearEndCopyEn;

export const payrollYearEndCopyByLocale: Record<FlowLocale, PayrollYearEndCopy> = {
  ko: {
    ...yearEndCopyEn,
    heroEyebrow: "FlowHR 관리자",
    title: "연말정산 및 원천징수영수증",
    description: "연말정산을 미리 확인하고 직원 원천징수영수증 발급 가능 상태를 점검합니다.",
    inputTitle: "입력",
    yearLabel: "연도",
    employeeIdLabel: "직원 번호",
    nonTaxableAnnualIncomeLabel: "비과세 연소득",
    earnedIncomeTaxCreditLabel: "근로소득세액공제",
    childTaxCreditLabel: "자녀세액공제",
    additionalTaxCreditLabel: "추가세액공제",
    annualIncomeTaxRateLabel: "연소득세율",
    localIncomeTaxRateLabel: "지방소득세율",
    issuerNameLabel: "발급자명",
    personalPensionLabel: "개인연금",
    insurancePremiumLabel: "보험료",
    medicalExpenseLabel: "의료비",
    educationExpenseLabel: "교육비",
    donationLabel: "기부금",
    housingSavingsLabel: "주택청약",
    personalPensionEligibleLabel: "개인연금 공제 가능",
    insurancePremiumEligibleLabel: "보험료 공제 가능",
    medicalExpenseEligibleLabel: "의료비 공제 가능",
    educationExpenseEligibleLabel: "교육비 공제 가능",
    donationEligibleLabel: "기부금 공제 가능",
    housingSavingsEligibleLabel: "주택청약 공제 가능",
    accessTokenLabel: "연결 토큰 (선택)",
    bearerTokenPlaceholder: "베어러 토큰",
    actorIdFallbackLabel: "관리자 계정 (개발용 대체값)",
    organizationIdFallbackLabel: "운영 조직 (개발용 대체값)",
    previewSettlementAction: "정산 프리뷰",
    recalculateSettlementAction: "정산 재계산",
    loadInsuranceReconciliationAction: "보험 정산 대사 불러오기",
    previewReceiptAction: "영수증 프리뷰",
    issueReceiptAction: "영수증 발급",
    sessionErrorPrefix: "세션 오류",
    settlementTitle: "정산 결과",
    noSettlementYet: "아직 정산 결과가 없습니다.",
    grossNetLabel: "총지급 / 실지급",
    inputVectorHashLabel: "입력 기준 스냅샷",
    taxCreditInputAppliedLabel: "세액공제 입력 / 적용",
    cappedTaxCreditsLabel: "상한 적용 세액공제",
    taxCreditReasonCodesLabel: "세액공제 적용 요약",
    taxLiabilityLabel: "연간 세액",
    priorWithheldLabel: "기납부 원천세",
    withholdingDeltaLabel: "원천세 차이",
    additionalWithholdingDueLabel: "추가 납부 필요액",
    withholdingRefundLabel: "환급액",
    previewedRunsLabel: "프리뷰 실행",
    recalculationTitle: "재계산",
    noRecalculationYet: "아직 재계산 결과가 없습니다.",
    incomeDeductionInputLabel: "소득공제 입력 합계",
    cappedDeductionLabel: "상한 적용 공제액",
    appliedDeductionLabel: "최종 적용 공제액",
    taxableIncomeLabel: "과세소득",
    cappedItemsLabel: "상한 적용 항목",
    deductionReasonCodesLabel: "공제 적용 요약",
    deductionEligibilityLabel: "공제 가능 항목",
    eligibilityBlockingReasonsLabel: "공제 차단 사유",
    taxLiabilityDeltaLabel: "세액 차이",
    withholdingDeltaChangeLabel: "원천세 차이 변경",
    additionalDueLabel: "추가 납부액",
    refundLabel: "환급액",
    insuranceReconciliationTitle: "보험 정산 대사",
    noInsuranceReconciliationReportYet: "아직 보험 정산 대사 결과가 없습니다.",
    statusLabel: "상태",
    annualSocialInsuranceRunsLabel: "연간 사회보험 합계(실행 기준)",
    comparedInsurancePremiumFinalizationLabel: "대사 대상 보험료(확정값)",
    deltaLabel: "차이",
    finalizationHashLabel: "최종확정 / 일치값",
    insuranceReasonCodeLabel: "보험 적용 요약",
    monthlyBreakdownLabel: "월별 상세",
    withholdingReceiptTitle: "원천징수영수증",
    noReceiptSummaryYet: "아직 영수증 요약이 없습니다.",
    receiptNumberLabel: "영수증 번호",
    canIssueIssuedLabel: "발급 가능 / 발급 완료",
    issuedAtLabel: "발급 시각",
    pendingReceiptRunsLabel: "수신 확인 대기 실행",
    blockingReasonsLabel: "차단 사유",
    accuracyEvidenceTitle: "계산 정확성 증빙",
    noAccuracyEvidenceYet: "정산/재계산/보험 대사를 실행하면 증빙이 생성됩니다.",
    accuracySummaryLabel: "증빙 요약",
    accuracyPassLabel: "통과",
    accuracyFailLabel: "실패",
    accuracyCheckLabels: {
      gross_net_balance: "총지급/실지급 균형",
      deduction_components_balance: "공제 항목 합계 균형",
      withholding_delta_balance: "원천세 차이 균형",
      due_refund_exclusive: "추가 납부/환급 상호배타",
      tax_credit_cap_balance: "세액공제 상한 균형",
      taxable_income_deduction_balance: "과세소득 공제 균형",
      tax_liability_delta_balance: "세액 차이 반영 균형",
      withholding_delta_change_balance: "원천세 차이 변경 균형",
      taxable_income_reduction_balance: "과세소득 감소량 균형",
      settlement_recalculation_baseline_balance: "정산/재계산 기준 균형",
      insurance_reconciliation_status_balance: "보험 대사 상태 균형",
      insurance_monthly_sum_balance: "보험 월별 합계 균형"
    },
    apiLogsTitle: "요청 로그",
    apiLogsTotalLabel: "총",
    apiLogsSuccessLabel: "성공",
    apiLogsFailLabel: "실패",
    apiLogsRunningLabel: "실행 중",
    noApiCallYet: "아직 API 호출이 없습니다.",
    openPreflightChecklistAction: "프리플라이트 체크리스트 열기",
    backToAdminAction: "관리자 화면으로",
    statusRequestFailed: "요청을 완료하지 못했습니다. 현재 상태를 확인한 뒤 다시 시도해 주세요.",
    statusLoadedAnnualLiabilityPrefix: "연간 세액 로드 완료",
    statusRecalculatedTaxDeltaPrefix: "세액 차이 재계산 완료",
    statusLoadedInsuranceReconciliationPrefix: "보험 정산 대사 로드 완료",
    statusDeltaLabel: "차이",
    statusIssuedPrefix: "발급 완료",
    statusPreviewedPrefix: "프리뷰 완료",
    statusInvalidInput: "입력값을 다시 확인해 주세요.",
    statusNonNegativeInteger: "0 이상의 정수여야 합니다.",
    statusRateBetweenZeroAndOne: "0 이상 1 이하의 값이어야 합니다.",
    pendingSettlementPreview: "연말정산 프리뷰",
    pendingSettlementRecalculation: "연말정산 재계산",
    pendingReceiptIssue: "원천징수영수증 발급",
    pendingReceiptPreview: "원천징수영수증 프리뷰",
    pendingInsuranceReconciliation: "연말정산 보험 대사 조회",
    logPreviewSettlement: "연말정산 프리뷰",
    logRecalculateSettlement: "연말정산 재계산",
    logIssueReceipt: "원천징수영수증 발급",
    logPreviewReceipt: "원천징수영수증 프리뷰",
    logInsuranceReconciliation: "연말정산 보험 대사 조회",
    yesLabel: "예",
    noLabel: "아니오",
    okLabel: "성공",
    failLabel: "실패",
    capLabel: "상한",
    deductionItemLabels: {
      personalPensionKrw: "개인연금",
      insurancePremiumKrw: "보험료",
      medicalExpenseKrw: "의료비",
      educationExpenseKrw: "교육비",
      donationKrw: "기부금",
      housingSavingsKrw: "주택청약"
    },
    deductionEligibilityLabels: {
      personalPensionEligible: "개인연금",
      insurancePremiumEligible: "보험료",
      medicalExpenseEligible: "의료비",
      educationExpenseEligible: "교육비",
      donationEligible: "기부금",
      housingSavingsEligible: "주택청약"
    },
    taxCreditItemLabels: {
      earnedIncomeTaxCreditKrw: "근로소득세액공제",
      childTaxCreditKrw: "자녀세액공제",
      additionalTaxCreditKrw: "추가세액공제"
    }
  },
  en: yearEndCopyEn
};

const yearEndPreflightCopyEn = {
  heroEyebrow: "FlowHR Admin",
  title: "Payroll Year-End Preflight Checklist",
  description: "Validate finalize prerequisites and filing readiness before year-end settlement apply.",
  inputTitle: "Input",
  yearLabel: "Year",
  employeeIdLabel: "Employee number",
  nonTaxableAnnualIncomeLabel: "Non-taxable Annual Income",
  accessTokenLabel: "Connection token (optional)",
  bearerTokenPlaceholder: "Bearer token",
  actorIdFallbackLabel: "Admin account (dev fallback)",
  organizationIdFallbackLabel: "Organization (dev fallback)",
  loadPreflightChecklistAction: "Load Preflight Checklist",
  sessionErrorPrefix: "Session error",
  checklistSummaryTitle: "Checklist Summary",
  noChecklistLoadedYet: "No checklist loaded yet.",
  readyToFinalizeLabel: "Ready To Finalize",
  passFailWarnLabel: "Pass / Fail / Warn",
  annualGrossPayLabel: "Annual Gross Pay",
  runStatesLabel: "Run States",
  distributionStatesLabel: "Distribution States",
  submissionStatesLabel: "Submission States",
  settlementHashLabel: "Settlement Match Key",
  checksTitle: "Checks",
  noCheckEntriesYet: "No check entries yet.",
  apiLogsTitle: "API Logs",
  apiLogsTotalLabel: "total",
  apiLogsSuccessLabel: "success",
  apiLogsFailLabel: "fail",
  apiLogsRunningLabel: "running",
  noApiCallYet: "No API call yet.",
  backToYearEndAction: "Back to Year-End",
  backToAdminAction: "Back to Admin",
  statusRequestFailed: "We couldn't complete the request. Review the current state and try again.",
  statusLoadedChecklistReady: "loaded checklist (ready)",
  statusLoadedChecklistNotReady: "loaded checklist (not ready)",
  statusInvalidInput: "Review the entered values and try again.",
  statusNonNegativeInteger: "must be a non-negative integer",
  pendingPreflightChecklist: "year-end preflight checklist",
  logPreflightChecklist: "year-end preflight checklist",
  yesLabel: "YES",
  noLabel: "NO",
  passLabel: "PASS",
  failLabel: "FAIL",
  warnLabel: "WARN",
  totalLabel: "total",
  confirmedLabel: "confirmed",
  previewedLabel: "previewed",
  undistributedLabel: "undistributed",
  pendingReceiptLabel: "pending receipt",
  pendingLabel: "pending",
  rejectedLabel: "rejected",
  okLabel: "OK"
};

export type PayrollYearEndPreflightCopy = typeof yearEndPreflightCopyEn;

export const payrollYearEndPreflightCopyByLocale: Record<FlowLocale, PayrollYearEndPreflightCopy> = {
  ko: {
    ...yearEndPreflightCopyEn,
    heroEyebrow: "FlowHR 관리자",
    title: "연말정산 프리플라이트 체크리스트",
    description: "연말정산 확정 전 필수 조건과 신고 준비 상태를 점검합니다.",
    inputTitle: "입력",
    yearLabel: "연도",
    employeeIdLabel: "직원 번호",
    nonTaxableAnnualIncomeLabel: "비과세 연소득",
    accessTokenLabel: "연결 토큰 (선택)",
    bearerTokenPlaceholder: "베어러 토큰",
    actorIdFallbackLabel: "관리자 계정 (개발용 대체값)",
    organizationIdFallbackLabel: "운영 조직 (개발용 대체값)",
    loadPreflightChecklistAction: "프리플라이트 체크리스트 조회",
    sessionErrorPrefix: "세션 오류",
    checklistSummaryTitle: "체크리스트 요약",
    noChecklistLoadedYet: "아직 체크리스트를 조회하지 않았습니다.",
    readyToFinalizeLabel: "확정 가능 여부",
    passFailWarnLabel: "통과 / 실패 / 경고",
    annualGrossPayLabel: "연간 총지급",
    runStatesLabel: "실행 상태",
    distributionStatesLabel: "배포 상태",
    submissionStatesLabel: "신고 제출 상태",
    settlementHashLabel: "정산 일치값",
    checksTitle: "검증 항목",
    noCheckEntriesYet: "아직 검증 항목이 없습니다.",
    apiLogsTitle: "요청 로그",
    apiLogsTotalLabel: "총",
    apiLogsSuccessLabel: "성공",
    apiLogsFailLabel: "실패",
    apiLogsRunningLabel: "실행 중",
    noApiCallYet: "아직 API 호출이 없습니다.",
    backToYearEndAction: "연말정산 화면으로",
    backToAdminAction: "관리자 화면으로",
    statusRequestFailed: "요청을 완료하지 못했습니다. 현재 상태를 확인한 뒤 다시 시도해 주세요.",
    statusLoadedChecklistReady: "체크리스트 로드 완료 (확정 가능)",
    statusLoadedChecklistNotReady: "체크리스트 로드 완료 (확정 불가)",
    statusInvalidInput: "입력값을 다시 확인해 주세요.",
    statusNonNegativeInteger: "0 이상의 정수여야 합니다.",
    pendingPreflightChecklist: "연말정산 프리플라이트 체크리스트 조회",
    logPreflightChecklist: "연말정산 프리플라이트 체크리스트 조회",
    yesLabel: "예",
    noLabel: "아니오",
    passLabel: "통과",
    failLabel: "실패",
    warnLabel: "경고",
    totalLabel: "전체",
    confirmedLabel: "확정",
    previewedLabel: "프리뷰",
    undistributedLabel: "미배포",
    pendingReceiptLabel: "수신 대기",
    pendingLabel: "대기",
    rejectedLabel: "반려",
    okLabel: "성공"
  },
  en: yearEndPreflightCopyEn
};
