import { type FlowLocale } from "@/lib/i18n/locales";

const filingCopyEn = {
  heroEyebrow: "FlowHR Admin",
  title: "Payroll Year-End Finalization and Filing",
  description:
    "Finalize year-end settlement, manage filing submissions with clear filters, and review the submission timeline and evidence notes.",
  inputTitle: "Submission Setup",
  yearLabel: "Year",
  employeeIdLabel: "Employee number",
  nonTaxableAnnualIncomeLabel: "Non-taxable Annual Income",
  additionalTaxCreditLabel: "Additional Tax Credit",
  annualIncomeTaxRateLabel: "Annual Income Tax Rate",
  localIncomeTaxRateLabel: "Local Income Tax Rate",
  personalPensionLabel: "Personal Pension",
  insurancePremiumLabel: "Insurance Premium",
  medicalExpenseLabel: "Medical Expense",
  educationExpenseLabel: "Education Expense",
  donationLabel: "Donation",
  housingSavingsLabel: "Housing Savings",
  exportFormatLabel: "Export Format",
  validationModeLabel: "Validation Mode",
  submissionTransportLabel: "Submission Method",
  submissionStatusFilterLabel: "Submission Progress",
  ackStatusFilterLabel: "Response Status",
  validationStatusFilterLabel: "Validation Result",
  transportFilterLabel: "Submission Method",
  submissionSearchLabel: "Search",
  submissionSearchPlaceholder: "submission note, response note",
  settlementHashFilterLabel: "Settlement Match Filter",
  settlementHashFilterPlaceholder: "match key prefix (8-64 characters)",
  submissionSortByLabel: "Sort By",
  submissionSortDirectionLabel: "Sort Direction",
  clearHashFilterAction: "Clear Match Filter",
  hashPrefixLabel: "match key",
  finalizationNoteLabel: "Finalization Note",
  expectedSettlementHashExportLabel: "Settlement Match Key for Export/Submit",
  expectedSettlementHashAckLabel: "Settlement Match Key for Response Check",
  expectedSettlementHashPlaceholder: "optional settlement match key",
  submissionNoteLabel: "Submission Note",
  ackSubmissionIdLabel: "Submission to Review",
  ackStatusLabel: "Response Result",
  ackCodeLabel: "Response Category",
  defaultAcceptedResponseOptionLabel: "Default accept response",
  defaultRejectedResponseOptionLabel: "Default rejection response",
  defaultRejectionReasonOptionLabel: "Default rejection reason",
  rejectionReasonCodeLabel: "Rejection Category",
  rejectionDetailLabel: "Rejection Detail",
  ackNoteLabel: "Response Note",
  resubmitSubmissionIdLabel: "Submission to Resubmit",
  resubmissionReasonLabel: "Resubmission Reason",
  cancelSubmissionIdLabel: "Submission to Cancel",
  reopenSubmissionIdLabel: "Submission to Reopen",
  timelineSubmissionIdLabel: "Submission for Timeline",
  evidenceNoteLabel: "Evidence Note",
  accessTokenLabel: "Connection token (optional)",
  bearerTokenPlaceholder: "Bearer token",
  actorIdFallbackLabel: "Admin account (dev fallback)",
  organizationIdFallbackLabel: "Organization (dev fallback)",
  previewFinalizationAction: "Preview Finalization",
  finalizeSettlementAction: "Finalize Settlement",
  exportFilingDataAction: "Export Filing Data",
  submitFilingPackageAction: "Submit Filing Package",
  acknowledgeSubmissionAction: "Save Response Result",
  resubmitSubmissionAction: "Resubmit Submission",
  cancelSubmissionAction: "Cancel Submission",
  reopenSubmissionAction: "Reopen Submission",
  refreshSubmissionsAction: "Refresh Submissions",
  resetFiltersAction: "Reset Filters",
  loadAckCatalogAction: "Load Response Catalog",
  loadSubmissionTimelineAction: "Load Submission Timeline",
  addEvidenceNoteAction: "Add Evidence Note",
  sessionErrorPrefix: "Session error",
  finalizationPanelTitle: "Finalization",
  noFinalizationSummaryYet: "No finalization summary yet.",
  canFinalizeFinalizedLabel: "Can Finalize / Finalized",
  finalizationIdLabel: "Finalization ID",
  settlementHashLabel: "Settlement Match Key",
  taxLiabilityLabel: "Tax Liability",
  withholdingDeltaLabel: "Withholding Delta",
  appliedDeductionLabel: "Applied Deduction",
  blockingReasonsLabel: "Blocking Reasons",
  filingExportPanelTitle: "Filing Export",
  noExportYet: "No export yet.",
  formatLabel: "Format",
  validationModeDisplayLabel: "Validation Mode",
  validationStatusLabel: "Validation Status",
  exportedRecordsLabel: "Exported Records",
  csvLabel: "CSV",
  artifactLabel: "Artifact",
  checksumLabel: "Checksum",
  validationIssuesLabel: "Validation Issues",
  apiLogsPanelTitle: "API Logs",
  apiLogsTotalLabel: "total",
  apiLogsSuccessLabel: "success",
  apiLogsFailLabel: "fail",
  apiLogsRunningLabel: "running",
  noApiCallYet: "No API call yet.",
  openFilingOpsDashboardAction: "Open Filing Ops Dashboard",
  backToYearEndAction: "Back to Year-End",
  backToAdminAction: "Back to Admin",
  filingSubmissionsPanelTitle: "Filing Submissions",
  noSubmissionSummaryYet: "No submission summary yet. Run Refresh Submissions.",
  totalFilteredLabel: "Total / Filtered",
  statusSummaryLabel: "Submission Progress",
  ackStatusSummaryLabel: "Response Status",
  validationSummaryLabel: "Validation",
  transportSummaryLabel: "Submission Method",
  activeFiltersLabel: "Active Filters",
  noFilingSubmissionYet: "No filing submission yet.",
  noSubmissionMatchesFilters: "No submissions match current filters.",
  quickAckAcceptedAction: "Quick Accept",
  quickCancelAction: "Quick Cancel",
  quickResubmitAction: "Quick Resubmit",
  quickReopenAction: "Quick Reopen",
  timelineAction: "Timeline",
  resubmissionOfLabel: "Resubmitted from",
  submissionTimelinePanelTitle: "Submission Timeline",
  noTimelineLoaded: "No timeline loaded.",
  failureActionPanelTitle: "Failure Follow-up Actions",
  latestFailureActionLabel: "Last Failed Action",
  latestFailureStatusLabel: "Status Code",
  latestFailureAtLabel: "Failed At",
  retryFailureAction: "Retry Failed Action",
  clearFailureAction: "Clear Failure",
  statusRequestFailed: "We couldn't complete the request. Review the current state and try again.",
  statusInvalidInput: "Review the entered values and try again.",
  statusFieldMustBeNonNegativeInteger: "must be a non-negative integer",
  statusFieldRateBetweenZeroAndOne: "must be between 0 and 1",
  statusPreviewLoaded: "preview loaded",
  statusFinalizedPrefix: "finalization saved",
  statusExportedPrefix: "export completed",
  statusSubmittedPrefix: "submission created",
  statusLoadedSubmissionsPrefix: "submission list loaded",
  statusLoadedAckCatalogPrefix: "response catalog loaded",
  statusAcknowledgedPrefix: "response saved",
  statusResubmittedPrefix: "submission resubmitted",
  statusCanceledPrefix: "submission canceled",
  statusReopenedPrefix: "submission reopened",
  statusLoadedTimelinePrefix: "timeline loaded",
  statusAddedEvidencePrefix: "evidence note saved for",
  statusAckSubmissionIdRequired: "Choose the submission to review.",
  statusResubmitSubmissionIdRequired: "Choose the submission to resubmit.",
  statusCancelSubmissionIdRequired: "Choose the submission to cancel.",
  statusReopenSubmissionIdRequired: "Choose the submission to reopen.",
  statusTimelineSubmissionIdRequired: "Choose the submission to inspect.",
  statusTimelineSubmissionIdRequiredForEvidence: "Choose the submission before adding an evidence note.",
  pendingFinalizationApply: "saving year-end finalization",
  pendingFinalizationPreview: "loading finalization preview",
  pendingFilingExport: "exporting filing data",
  pendingSubmitPackage: "submitting filing package",
  pendingListSubmissions: "loading filing submissions",
  pendingAckCatalog: "loading response catalog",
  pendingAckSubmission: "saving response result",
  pendingResubmitSubmission: "resubmitting filing package",
  pendingCancelSubmission: "canceling filing package",
  pendingReopenSubmission: "reopening filing package",
  pendingLoadTimeline: "loading submission timeline",
  pendingAddEvidence: "saving evidence note",
  logFinalizeSettlement: "finalize settlement",
  logPreviewFinalization: "preview finalization",
  logExportFilingData: "export filing data",
  logSubmitFilingPackage: "submit filing package",
  logListFilingSubmissions: "list filing submissions",
  logListAckCatalog: "list response catalog",
  logAcknowledgeSubmission: "save response result",
  logResubmitSubmission: "resubmit filing package",
  logCancelSubmission: "cancel filing package",
  logReopenSubmission: "reopen filing package",
  logListSubmissionTimeline: "list submission timeline",
  logAddEvidenceNote: "add evidence note",
  yesLabel: "YES",
  noLabel: "NO",
  okLabel: "OK",
  failLabel: "FAIL",
  readyLabel: "ready",
  dashLabel: "-",
  transportShortManualLabel: "manual",
  transportShortHometaxLabel: "hometax",
  transportShortNtsApiMockLabel: "mock API",
  exportFormatOptionLabels: {
    json: "JSON",
    csv: "CSV",
    jsonl: "JSONL",
    hometax_csv: "Hometax CSV"
  } as Record<string, string>,
  validationModeOptionLabels: {
    basic: "Basic",
    strict: "Strict"
  } as Record<string, string>,
  submissionTransportOptionLabels: {
    manual_portal: "Manual portal",
    hometax_upload: "Hometax upload",
    nts_api_mock: "Mock API",
    all: "All"
  } as Record<string, string>,
  submissionStatusOptionLabels: {
    all: "All",
    submitted: "Submitted",
    acknowledged: "Response saved",
    canceled: "Canceled"
  } as Record<string, string>,
  ackStatusOptionLabels: {
    all: "All",
    accepted: "Accepted",
    rejected: "Rejected",
    none: "No response"
  } as Record<string, string>,
  validationStatusOptionLabels: {
    all: "All",
    pass: "Passed",
    fail: "Failed"
  } as Record<string, string>,
  submissionSortByOptionLabels: {
    submittedAt: "Submitted at",
    attempt: "Attempt",
    status: "Submission progress",
    ackStatus: "Response status",
    validationStatus: "Validation result",
    transport: "Submission method"
  } as Record<string, string>,
  submissionSortDirectionOptionLabels: {
    desc: "Newest first",
    asc: "Oldest first"
  } as Record<string, string>,
  submissionStatusBadgeLabels: {
    submitted: "SUBMITTED",
    acknowledged: "RESPONDED",
    canceled: "CANCELED"
  } as Record<string, string>,
  timelineActionBadgeLabels: {
    submitted: "submitted",
    resubmitted: "resubmitted",
    acknowledged: "response saved",
    canceled: "canceled",
    reopened: "reopened",
    evidence_note_added: "evidence note"
  } as Record<string, string>,
  timelineAttemptLabel: "attempt",
  timelineFromLabel: "from",
  timelineReasonLabel: "reason",
  timelineNoteLabel: "note",
  timelineAckPrefix: "Response",
  timelineReasonCodeLabel: "category",
  timelineDetailLabel: "detail",
  timelineCanceledLabel: "SUBMISSION CANCELED",
  timelineReopenedLabel: "SUBMISSION REOPENED",
  timelineEvidencePrefix: "EVIDENCE NOTE"
};

export type PayrollYearEndFilingCopy = typeof filingCopyEn;

export const payrollYearEndFilingCopyByLocale: Record<FlowLocale, PayrollYearEndFilingCopy> = {
  ko: {
    ...filingCopyEn,
    heroEyebrow: "FlowHR 관리자",
    title: "연말정산 확정 및 신고 관리",
    description:
      "연말정산을 확정하고, 신고 제출 현황을 명확한 필터로 관리하며, 제출 이력과 증빙 메모를 확인합니다.",
    inputTitle: "신고 준비",
    yearLabel: "연도",
    employeeIdLabel: "직원 번호",
    nonTaxableAnnualIncomeLabel: "비과세 연간 소득",
    additionalTaxCreditLabel: "추가 세액공제",
    annualIncomeTaxRateLabel: "연 소득세율",
    localIncomeTaxRateLabel: "지방소득세율",
    personalPensionLabel: "개인연금",
    insurancePremiumLabel: "보험료",
    medicalExpenseLabel: "의료비",
    educationExpenseLabel: "교육비",
    donationLabel: "기부금",
    housingSavingsLabel: "주택저축",
    exportFormatLabel: "내보내기 형식",
    validationModeLabel: "검증 방식",
    submissionTransportLabel: "제출 방식",
    submissionStatusFilterLabel: "제출 진행 상태",
    ackStatusFilterLabel: "응답 처리 상태",
    validationStatusFilterLabel: "검증 결과",
    transportFilterLabel: "제출 방식",
    submissionSearchLabel: "검색",
    submissionSearchPlaceholder: "제출 메모, 처리 메모",
    settlementHashFilterLabel: "정산 일치값 필터",
    settlementHashFilterPlaceholder: "일치값 앞부분 (8-64자리)",
    submissionSortByLabel: "정렬 기준",
    submissionSortDirectionLabel: "정렬 방향",
    clearHashFilterAction: "일치값 필터 초기화",
    hashPrefixLabel: "일치값",
    finalizationNoteLabel: "확정 메모",
    expectedSettlementHashExportLabel: "내보내기/제출용 정산 일치값",
    expectedSettlementHashAckLabel: "응답 확인용 정산 일치값",
    expectedSettlementHashPlaceholder: "정산 일치값을 입력하세요(선택)",
    submissionNoteLabel: "제출 메모",
    ackSubmissionIdLabel: "처리할 제출 건",
    ackStatusLabel: "응답 결과",
    ackCodeLabel: "응답 분류",
    defaultAcceptedResponseOptionLabel: "기본 승인 응답",
    defaultRejectedResponseOptionLabel: "기본 반려 응답",
    defaultRejectionReasonOptionLabel: "기본 반려 사유",
    rejectionReasonCodeLabel: "반려 분류",
    rejectionDetailLabel: "반려 상세 사유",
    ackNoteLabel: "응답 메모",
    resubmitSubmissionIdLabel: "재제출할 제출 건",
    resubmissionReasonLabel: "재제출 사유",
    cancelSubmissionIdLabel: "취소할 제출 건",
    reopenSubmissionIdLabel: "재개할 제출 건",
    timelineSubmissionIdLabel: "이력을 볼 제출 건",
    evidenceNoteLabel: "증빙 메모",
    accessTokenLabel: "연결 토큰(선택)",
    bearerTokenPlaceholder: "Bearer 토큰",
    actorIdFallbackLabel: "관리자 계정(개발용 대체값)",
    organizationIdFallbackLabel: "운영 조직(개발용 대체값)",
    previewFinalizationAction: "확정 미리보기",
    finalizeSettlementAction: "정산 확정",
    exportFilingDataAction: "신고 데이터 내보내기",
    submitFilingPackageAction: "신고 제출",
    acknowledgeSubmissionAction: "응답 결과 저장",
    resubmitSubmissionAction: "재제출",
    cancelSubmissionAction: "제출 취소",
    reopenSubmissionAction: "제출 재개",
    refreshSubmissionsAction: "제출 목록 새로고침",
    resetFiltersAction: "필터 초기화",
    loadAckCatalogAction: "응답 분류표 불러오기",
    loadSubmissionTimelineAction: "제출 이력 불러오기",
    addEvidenceNoteAction: "증빙 메모 추가",
    sessionErrorPrefix: "세션 오류",
    finalizationPanelTitle: "확정 결과",
    noFinalizationSummaryYet: "아직 확정 결과가 없습니다.",
    canFinalizeFinalizedLabel: "확정 가능 / 확정 완료",
    finalizationIdLabel: "확정 ID",
    settlementHashLabel: "정산 일치값",
    taxLiabilityLabel: "연간 세액",
    withholdingDeltaLabel: "원천징수 차액",
    appliedDeductionLabel: "적용 공제",
    blockingReasonsLabel: "차단 사유",
    filingExportPanelTitle: "신고 내보내기",
    noExportYet: "아직 내보내기 결과가 없습니다.",
    formatLabel: "형식",
    validationModeDisplayLabel: "검증 방식",
    validationStatusLabel: "검증 상태",
    exportedRecordsLabel: "내보낸 항목 수",
    csvLabel: "CSV",
    artifactLabel: "산출물",
    checksumLabel: "체크섬",
    validationIssuesLabel: "검증 이슈",
    apiLogsPanelTitle: "요청 로그",
    apiLogsTotalLabel: "전체",
    apiLogsSuccessLabel: "성공",
    apiLogsFailLabel: "실패",
    apiLogsRunningLabel: "진행 중",
    noApiCallYet: "아직 API 호출이 없습니다.",
    openFilingOpsDashboardAction: "신고 운영 대시보드 열기",
    backToYearEndAction: "연말정산으로 돌아가기",
    backToAdminAction: "관리자로 돌아가기",
    filingSubmissionsPanelTitle: "신고 제출 목록",
    noSubmissionSummaryYet: "아직 제출 요약이 없습니다. 제출 목록 새로고침을 실행해 주세요.",
    totalFilteredLabel: "전체 / 필터 결과",
    statusSummaryLabel: "제출 진행 상태",
    ackStatusSummaryLabel: "응답 처리 상태",
    validationSummaryLabel: "검증 결과",
    transportSummaryLabel: "제출 방식",
    activeFiltersLabel: "현재 필터",
    noFilingSubmissionYet: "아직 신고 제출 이력이 없습니다.",
    noSubmissionMatchesFilters: "현재 필터와 일치하는 제출 건이 없습니다.",
    quickAckAcceptedAction: "바로 승인",
    quickCancelAction: "바로 취소",
    quickResubmitAction: "바로 재제출",
    quickReopenAction: "바로 재개",
    timelineAction: "이력 보기",
    resubmissionOfLabel: "이전 제출",
    submissionTimelinePanelTitle: "제출 이력",
    noTimelineLoaded: "불러온 제출 이력이 없습니다.",
    failureActionPanelTitle: "실패 후속 조치",
    latestFailureActionLabel: "최근 실패 작업",
    latestFailureStatusLabel: "응답 상태",
    latestFailureAtLabel: "실패 시각",
    retryFailureAction: "같은 작업 다시 시도",
    clearFailureAction: "실패 기록 지우기",
    statusRequestFailed: "요청을 완료하지 못했습니다. 현재 상태를 확인한 뒤 다시 시도해 주세요.",
    statusInvalidInput: "입력값을 다시 확인해 주세요.",
    statusFieldMustBeNonNegativeInteger: "0 이상의 정수여야 합니다",
    statusFieldRateBetweenZeroAndOne: "0 이상 1 이하 값이어야 합니다",
    statusPreviewLoaded: "미리보기를 불러왔습니다",
    statusFinalizedPrefix: "정산 확정을 저장했습니다",
    statusExportedPrefix: "내보내기를 완료했습니다",
    statusSubmittedPrefix: "제출을 생성했습니다",
    statusLoadedSubmissionsPrefix: "제출 목록을 불러왔습니다",
    statusLoadedAckCatalogPrefix: "응답 분류표를 불러왔습니다",
    statusAcknowledgedPrefix: "응답 처리를 저장했습니다",
    statusResubmittedPrefix: "재제출을 완료했습니다",
    statusCanceledPrefix: "제출을 취소했습니다",
    statusReopenedPrefix: "제출을 다시 열었습니다",
    statusLoadedTimelinePrefix: "제출 이력을 불러왔습니다",
    statusAddedEvidencePrefix: "증빙 메모를 저장했습니다",
    statusAckSubmissionIdRequired: "처리할 제출 건을 선택해 주세요.",
    statusResubmitSubmissionIdRequired: "재제출할 제출 건을 선택해 주세요.",
    statusCancelSubmissionIdRequired: "취소할 제출 건을 선택해 주세요.",
    statusReopenSubmissionIdRequired: "재개할 제출 건을 선택해 주세요.",
    statusTimelineSubmissionIdRequired: "이력을 확인할 제출 건을 선택해 주세요.",
    statusTimelineSubmissionIdRequiredForEvidence: "증빙 메모를 추가할 제출 건을 먼저 선택해 주세요.",
    pendingFinalizationApply: "연말정산 확정을 저장하고 있습니다",
    pendingFinalizationPreview: "확정 미리보기를 불러오고 있습니다",
    pendingFilingExport: "신고 데이터를 내보내고 있습니다",
    pendingSubmitPackage: "신고를 제출하고 있습니다",
    pendingListSubmissions: "제출 목록을 불러오고 있습니다",
    pendingAckCatalog: "응답 분류표를 불러오고 있습니다",
    pendingAckSubmission: "응답 결과를 저장하고 있습니다",
    pendingResubmitSubmission: "제출을 다시 보내고 있습니다",
    pendingCancelSubmission: "제출을 취소하고 있습니다",
    pendingReopenSubmission: "제출을 다시 열고 있습니다",
    pendingLoadTimeline: "제출 이력을 불러오고 있습니다",
    pendingAddEvidence: "증빙 메모를 저장하고 있습니다",
    logFinalizeSettlement: "정산 확정",
    logPreviewFinalization: "확정 미리보기",
    logExportFilingData: "신고 데이터 내보내기",
    logSubmitFilingPackage: "신고 제출",
    logListFilingSubmissions: "제출 목록 조회",
    logListAckCatalog: "응답 분류표 조회",
    logAcknowledgeSubmission: "응답 결과 저장",
    logResubmitSubmission: "재제출",
    logCancelSubmission: "제출 취소",
    logReopenSubmission: "제출 재개",
    logListSubmissionTimeline: "제출 이력 조회",
    logAddEvidenceNote: "증빙 메모 추가",
    yesLabel: "예",
    noLabel: "아니오",
    okLabel: "성공",
    failLabel: "실패",
    readyLabel: "준비됨",
    transportShortManualLabel: "수동",
    transportShortHometaxLabel: "홈택스",
    transportShortNtsApiMockLabel: "모의 API",
    submissionTransportOptionLabels: {
      manual_portal: "수동 제출",
      hometax_upload: "홈택스 업로드",
      nts_api_mock: "모의 API",
      all: "전체"
    },
    exportFormatOptionLabels: {
      json: "JSON",
      csv: "CSV",
      jsonl: "JSONL",
      hometax_csv: "홈택스 CSV"
    },
    validationModeOptionLabels: {
      basic: "기본",
      strict: "엄격"
    },
    submissionStatusOptionLabels: {
      all: "전체",
      submitted: "제출 완료",
      acknowledged: "응답 처리 완료",
      canceled: "취소됨"
    },
    ackStatusOptionLabels: {
      all: "전체",
      accepted: "승인",
      rejected: "반려",
      none: "응답 없음"
    },
    validationStatusOptionLabels: {
      all: "전체",
      pass: "통과",
      fail: "실패"
    },
    submissionSortByOptionLabels: {
      submittedAt: "제출 시각",
      attempt: "시도 횟수",
      status: "제출 진행 상태",
      ackStatus: "응답 처리 상태",
      validationStatus: "검증 결과",
      transport: "제출 방식"
    },
    submissionSortDirectionOptionLabels: {
      desc: "최신순",
      asc: "오래된순"
    },
    submissionStatusBadgeLabels: {
      submitted: "제출 완료",
      acknowledged: "응답 저장",
      canceled: "취소됨"
    },
    timelineActionBadgeLabels: {
      submitted: "제출",
      resubmitted: "재제출",
      acknowledged: "응답 저장",
      canceled: "취소",
      reopened: "재개",
      evidence_note_added: "증빙 메모"
    },
    timelineAttemptLabel: "시도",
    timelineFromLabel: "이전 제출",
    timelineReasonLabel: "사유",
    timelineNoteLabel: "메모",
    timelineAckPrefix: "응답",
    timelineReasonCodeLabel: "분류",
    timelineDetailLabel: "상세",
    timelineCanceledLabel: "제출 취소",
    timelineReopenedLabel: "제출 재개",
    timelineEvidencePrefix: "증빙 메모"
  },
  en: filingCopyEn
};
