import { type FlowLocale } from "@/lib/i18n/locales";

const filingCopyEn = {
  heroEyebrow: "FlowHR Admin",
  title: "Payroll Year-End Finalization and Filing Console",
  description:
    "Finalize year-end settlement, manage filing submissions with status/search/sort filters, and trace timeline/evidence notes.",
  inputTitle: "Input",
  yearLabel: "Year",
  employeeIdLabel: "Employee ID",
  nonTaxableAnnualIncomeLabel: "Non-taxable Annual Income",
  additionalTaxCreditLabel: "Additional Tax Credit",
  annualIncomeTaxRateLabel: "Annual Income Tax Rate",
  localIncomeTaxRateLabel: "Local Income Tax Rate",
  personalPensionLabel: "Personal Pension",
  insurancePremiumLabel: "Insurance Premium",
  medicalExpenseLabel: "Medical Expense",
  educationExpenseLabel: "Education Expense",
  donationLabel: "Donation",
  housingSavingsLabel: "Housing Savings",
  exportFormatLabel: "Export Format",
  validationModeLabel: "Validation Mode",
  submissionTransportLabel: "Submission Transport",
  submissionStatusFilterLabel: "Submission Status Filter",
  ackStatusFilterLabel: "ACK Status Filter",
  validationStatusFilterLabel: "Validation Status Filter",
  transportFilterLabel: "Transport Filter",
  submissionSearchLabel: "Submission Search",
  submissionSearchPlaceholder: "submissionId, ackCode, note",
  settlementHashFilterLabel: "Settlement Hash Filter",
  settlementHashFilterPlaceholder: "hash prefix (8-64 hex)",
  submissionSortByLabel: "Submission Sort By",
  submissionSortDirectionLabel: "Submission Sort Direction",
  clearHashFilterAction: "Clear Hash Filter",
  hashPrefixLabel: "hash",
  finalizationNoteLabel: "Finalization Note",
  expectedSettlementHashExportLabel: "Expected Settlement Hash (Export/Submit Guard)",
  expectedSettlementHashAckLabel: "Expected Settlement Hash (ACK Guard)",
  expectedSettlementHashPlaceholder: "64-char sha256 hash (optional)",
  submissionNoteLabel: "Submission Note",
  ackSubmissionIdLabel: "Ack Submission ID",
  ackStatusLabel: "Ack Status",
  ackCodeLabel: "Ack Code",
  rejectionReasonCodeLabel: "Rejection Reason Code",
  rejectionDetailLabel: "Rejection Detail",
  ackNoteLabel: "Ack Note",
  resubmitSubmissionIdLabel: "Resubmit Submission ID",
  resubmissionReasonLabel: "Resubmission Reason",
  cancelSubmissionIdLabel: "Cancel Submission ID",
  reopenSubmissionIdLabel: "Reopen Submission ID",
  timelineSubmissionIdLabel: "Timeline Submission ID",
  evidenceNoteLabel: "Evidence Note",
  accessTokenLabel: "Access Token (optional)",
  bearerTokenPlaceholder: "Bearer token",
  actorIdFallbackLabel: "Actor ID (dev fallback)",
  organizationIdFallbackLabel: "Organization ID (dev fallback)",
  previewFinalizationAction: "Preview Finalization",
  finalizeSettlementAction: "Finalize Settlement",
  exportFilingDataAction: "Export Filing Data",
  submitFilingPackageAction: "Submit Filing Package",
  acknowledgeSubmissionAction: "Acknowledge Submission",
  resubmitSubmissionAction: "Resubmit Submission",
  cancelSubmissionAction: "Cancel Submission",
  reopenSubmissionAction: "Reopen Submission",
  refreshSubmissionsAction: "Refresh Submissions",
  resetFiltersAction: "Reset Filters",
  loadAckCatalogAction: "Load ACK Catalog",
  loadSubmissionTimelineAction: "Load Submission Timeline",
  addEvidenceNoteAction: "Add Evidence Note",
  sessionErrorPrefix: "Session error",
  finalizationPanelTitle: "Finalization",
  noFinalizationSummaryYet: "No finalization summary yet.",
  canFinalizeFinalizedLabel: "Can Finalize / Finalized",
  finalizationIdLabel: "Finalization ID",
  settlementHashLabel: "Settlement Hash",
  taxLiabilityLabel: "Tax Liability",
  withholdingDeltaLabel: "Withholding Delta",
  appliedDeductionLabel: "Applied Deduction",
  blockingReasonsLabel: "Blocking Reasons",
  filingExportPanelTitle: "Filing Export",
  noExportYet: "No export yet.",
  formatLabel: "Format",
  validationModeDisplayLabel: "Validation Mode",
  validationStatusLabel: "Validation Status",
  exportedRecordsLabel: "Exported Records",
  csvLabel: "CSV",
  artifactLabel: "Artifact",
  checksumLabel: "Checksum",
  validationIssuesLabel: "Validation Issues",
  apiLogsPanelTitle: "API Logs",
  apiLogsTotalLabel: "total",
  apiLogsSuccessLabel: "success",
  apiLogsFailLabel: "fail",
  apiLogsRunningLabel: "running",
  noApiCallYet: "No API call yet.",
  openFilingOpsDashboardAction: "Open Filing Ops Dashboard",
  backToYearEndAction: "Back to Year-End",
  backToAdminAction: "Back to Admin",
  filingSubmissionsPanelTitle: "Filing Submissions",
  noSubmissionSummaryYet: "No submission summary yet. Run Refresh Submissions.",
  totalFilteredLabel: "Total / Filtered",
  statusSummaryLabel: "Status",
  ackStatusSummaryLabel: "ACK Status",
  validationSummaryLabel: "Validation",
  transportSummaryLabel: "Transport",
  activeFiltersLabel: "Active Filters",
  noFilingSubmissionYet: "No filing submission yet.",
  noSubmissionMatchesFilters: "No submissions match current filters.",
  quickAckAcceptedAction: "Quick ACK Accepted",
  quickCancelAction: "Quick Cancel",
  quickResubmitAction: "Quick Resubmit",
  quickReopenAction: "Quick Reopen",
  timelineAction: "Timeline",
  resubmissionOfLabel: "resubmissionOf",
  submissionTimelinePanelTitle: "Submission Timeline",
  noTimelineLoaded: "No timeline loaded.",
  statusRequestFailed: "request failed; check logs",
  statusInvalidInput: "invalid input",
  statusFieldMustBeNonNegativeInteger: "must be a non-negative integer",
  statusFieldRateBetweenZeroAndOne: "must be between 0 and 1",
  statusPreviewLoaded: "preview loaded",
  statusFinalizedPrefix: "finalized",
  statusExportedPrefix: "exported",
  statusSubmittedPrefix: "submitted",
  statusLoadedSubmissionsPrefix: "loaded",
  statusLoadedAckCatalogPrefix: "loaded ack catalog",
  statusAcknowledgedPrefix: "acknowledged",
  statusResubmittedPrefix: "resubmitted",
  statusCanceledPrefix: "canceled",
  statusReopenedPrefix: "reopened",
  statusLoadedTimelinePrefix: "loaded timeline",
  statusAddedEvidencePrefix: "added evidence note for",
  statusAckSubmissionIdRequired: "ack submission ID is required",
  statusResubmitSubmissionIdRequired: "resubmit submission ID is required",
  statusCancelSubmissionIdRequired: "cancel submission ID is required",
  statusReopenSubmissionIdRequired: "reopen submission ID is required",
  statusTimelineSubmissionIdRequired: "timeline submission ID is required",
  statusTimelineSubmissionIdRequiredForEvidence: "timeline submission ID is required for evidence note",
  pendingFinalizationApply: "year-end finalization apply",
  pendingFinalizationPreview: "year-end finalization preview",
  pendingFilingExport: "year-end filing export",
  pendingSubmitPackage: "year-end filing package submit",
  pendingListSubmissions: "year-end filing submissions list",
  pendingAckCatalog: "year-end filing ack catalog",
  pendingAckSubmission: "year-end filing package ack",
  pendingResubmitSubmission: "year-end filing package resubmit",
  pendingCancelSubmission: "year-end filing package cancel",
  pendingReopenSubmission: "year-end filing package reopen",
  pendingLoadTimeline: "year-end filing submission timeline",
  pendingAddEvidence: "year-end filing evidence note",
  logFinalizeSettlement: "finalize settlement",
  logPreviewFinalization: "preview finalization",
  logExportFilingData: "export filing data",
  logSubmitFilingPackage: "submit filing package",
  logListFilingSubmissions: "list filing submissions",
  logListAckCatalog: "list filing ack catalog",
  logAcknowledgeSubmission: "ack filing package",
  logResubmitSubmission: "resubmit filing package",
  logCancelSubmission: "cancel filing package",
  logReopenSubmission: "reopen filing package",
  logListSubmissionTimeline: "list filing submission timeline",
  logAddEvidenceNote: "add filing evidence note",
  yesLabel: "YES",
  noLabel: "NO",
  okLabel: "OK",
  failLabel: "FAIL",
  readyLabel: "ready",
  dashLabel: "-",
  transportShortManualLabel: "manual",
  transportShortHometaxLabel: "hometax",
  transportShortNtsApiMockLabel: "nts-api",
  exportFormatOptionLabels: {
    json: "json",
    csv: "csv",
    jsonl: "jsonl",
    hometax_csv: "hometax_csv"
  } as Record<string, string>,
  validationModeOptionLabels: {
    basic: "basic",
    strict: "strict"
  } as Record<string, string>,
  submissionTransportOptionLabels: {
    manual_portal: "manual_portal",
    hometax_upload: "hometax_upload",
    nts_api_mock: "nts_api_mock",
    all: "all"
  } as Record<string, string>,
  submissionStatusOptionLabels: {
    all: "all",
    submitted: "submitted",
    acknowledged: "acknowledged",
    canceled: "canceled"
  } as Record<string, string>,
  ackStatusOptionLabels: {
    all: "all",
    accepted: "accepted",
    rejected: "rejected",
    none: "none"
  } as Record<string, string>,
  validationStatusOptionLabels: {
    all: "all",
    pass: "pass",
    fail: "fail"
  } as Record<string, string>,
  submissionSortByOptionLabels: {
    submittedAt: "submittedAt",
    attempt: "attempt",
    status: "status",
    ackStatus: "ackStatus",
    validationStatus: "validationStatus",
    transport: "transport"
  } as Record<string, string>,
  submissionSortDirectionOptionLabels: {
    desc: "desc",
    asc: "asc"
  } as Record<string, string>,
  submissionStatusBadgeLabels: {
    submitted: "SUBMITTED",
    acknowledged: "ACKNOWLEDGED",
    canceled: "CANCELED"
  } as Record<string, string>,
  timelineActionBadgeLabels: {
    submitted: "submitted",
    resubmitted: "resubmitted",
    acknowledged: "acknowledged",
    canceled: "canceled",
    reopened: "reopened",
    evidence_note_added: "evidence_note_added"
  } as Record<string, string>,
  timelineAttemptLabel: "attempt",
  timelineFromLabel: "from",
  timelineReasonLabel: "reason",
  timelineNoteLabel: "note",
  timelineAckPrefix: "ACK",
  timelineReasonCodeLabel: "reason",
  timelineDetailLabel: "detail",
  timelineCanceledLabel: "SUBMISSION CANCELED",
  timelineReopenedLabel: "SUBMISSION REOPENED",
  timelineEvidencePrefix: "EVIDENCE NOTE"
};

export type PayrollYearEndFilingCopy = typeof filingCopyEn;

export const payrollYearEndFilingCopyByLocale: Record<FlowLocale, PayrollYearEndFilingCopy> = {
  ko: {
    ...filingCopyEn,
    heroEyebrow: "FlowHR 관리자",
    title: "연말정산 확정 및 신고 콘솔",
    description:
      "연말정산 확정을 실행하고, 신고 제출 이력을 상태/검색/정렬로 관리하며, 타임라인과 증빙 메모를 추적합니다.",
    inputTitle: "입력",
    yearLabel: "연도",
    employeeIdLabel: "직원 번호",
    nonTaxableAnnualIncomeLabel: "비과세 연소득",
    additionalTaxCreditLabel: "추가 세액공제",
    annualIncomeTaxRateLabel: "소득세율",
    localIncomeTaxRateLabel: "지방소득세율",
    personalPensionLabel: "개인연금",
    insurancePremiumLabel: "보험료",
    medicalExpenseLabel: "의료비",
    educationExpenseLabel: "교육비",
    donationLabel: "기부금",
    housingSavingsLabel: "주택청약",
    exportFormatLabel: "내보내기 형식",
    validationModeLabel: "검증 모드",
    submissionTransportLabel: "제출 전송 방식",
    submissionStatusFilterLabel: "제출 상태 필터",
    ackStatusFilterLabel: "ACK 상태 필터",
    validationStatusFilterLabel: "검증 상태 필터",
    transportFilterLabel: "전송 방식 필터",
    submissionSearchLabel: "제출 검색",
    submissionSearchPlaceholder: "제출 ID, ACK 코드, 메모",
    settlementHashFilterLabel: "정산 해시 필터",
    settlementHashFilterPlaceholder: "해시 접두어 (8-64자리 16진수)",
    submissionSortByLabel: "제출 정렬 기준",
    submissionSortDirectionLabel: "정렬 방향",
    clearHashFilterAction: "해시 필터 초기화",
    hashPrefixLabel: "해시",
    finalizationNoteLabel: "확정 메모",
    expectedSettlementHashExportLabel: "예상 정산 해시 (내보내기/제출 가드)",
    expectedSettlementHashAckLabel: "예상 정산 해시 (ACK 가드)",
    expectedSettlementHashPlaceholder: "64자리 sha256 해시 (선택)",
    submissionNoteLabel: "제출 메모",
    ackSubmissionIdLabel: "ACK 제출 ID",
    ackStatusLabel: "ACK 상태",
    ackCodeLabel: "ACK 코드",
    rejectionReasonCodeLabel: "반려 사유 코드",
    rejectionDetailLabel: "반려 상세 사유",
    ackNoteLabel: "ACK 메모",
    resubmitSubmissionIdLabel: "재제출 제출 ID",
    resubmissionReasonLabel: "재제출 사유",
    cancelSubmissionIdLabel: "취소 제출 ID",
    reopenSubmissionIdLabel: "재오픈 제출 ID",
    timelineSubmissionIdLabel: "타임라인 제출 ID",
    evidenceNoteLabel: "증빙 메모",
    accessTokenLabel: "액세스 토큰 (선택)",
    bearerTokenPlaceholder: "베어러 토큰",
    actorIdFallbackLabel: "액터 식별자 (개발용 대체값)",
    organizationIdFallbackLabel: "조직 식별자 (개발용 대체값)",
    previewFinalizationAction: "확정 프리뷰",
    finalizeSettlementAction: "정산 확정",
    exportFilingDataAction: "신고 데이터 내보내기",
    submitFilingPackageAction: "신고 패키지 제출",
    acknowledgeSubmissionAction: "제출 ACK 처리",
    resubmitSubmissionAction: "제출 재시도",
    cancelSubmissionAction: "제출 취소",
    reopenSubmissionAction: "제출 재오픈",
    refreshSubmissionsAction: "제출 목록 새로고침",
    resetFiltersAction: "필터 초기화",
    loadAckCatalogAction: "ACK 카탈로그 불러오기",
    loadSubmissionTimelineAction: "제출 타임라인 불러오기",
    addEvidenceNoteAction: "증빙 메모 추가",
    sessionErrorPrefix: "세션 오류",
    finalizationPanelTitle: "확정 결과",
    noFinalizationSummaryYet: "아직 확정 요약이 없습니다.",
    canFinalizeFinalizedLabel: "확정 가능 / 확정 완료",
    finalizationIdLabel: "확정 ID",
    settlementHashLabel: "정산 해시",
    taxLiabilityLabel: "연간 세액",
    withholdingDeltaLabel: "원천징수 차이",
    appliedDeductionLabel: "적용 공제액",
    blockingReasonsLabel: "차단 사유",
    filingExportPanelTitle: "신고 내보내기",
    noExportYet: "아직 내보내기 결과가 없습니다.",
    formatLabel: "형식",
    validationModeDisplayLabel: "검증 모드",
    validationStatusLabel: "검증 상태",
    exportedRecordsLabel: "내보낸 레코드 수",
    csvLabel: "CSV",
    artifactLabel: "아티팩트",
    checksumLabel: "체크섬",
    validationIssuesLabel: "검증 이슈",
    apiLogsPanelTitle: "요청 로그",
    apiLogsTotalLabel: "총",
    apiLogsSuccessLabel: "성공",
    apiLogsFailLabel: "실패",
    apiLogsRunningLabel: "실행중",
    noApiCallYet: "아직 API 호출이 없습니다.",
    openFilingOpsDashboardAction: "신고 운영 대시보드 열기",
    backToYearEndAction: "연말정산으로 돌아가기",
    backToAdminAction: "관리자 홈으로 돌아가기",
    filingSubmissionsPanelTitle: "신고 제출 목록",
    noSubmissionSummaryYet: "아직 제출 요약이 없습니다. 제출 목록 새로고침을 실행하세요.",
    totalFilteredLabel: "전체 / 필터 결과",
    statusSummaryLabel: "상태",
    ackStatusSummaryLabel: "ACK 상태",
    validationSummaryLabel: "검증",
    transportSummaryLabel: "전송",
    activeFiltersLabel: "현재 필터",
    noFilingSubmissionYet: "아직 신고 제출 이력이 없습니다.",
    noSubmissionMatchesFilters: "현재 필터 조건과 일치하는 제출이 없습니다.",
    quickAckAcceptedAction: "빠른 ACK 승인",
    quickCancelAction: "빠른 취소",
    quickResubmitAction: "빠른 재제출",
    quickReopenAction: "빠른 재오픈",
    timelineAction: "타임라인",
    resubmissionOfLabel: "재제출 원본",
    submissionTimelinePanelTitle: "제출 타임라인",
    noTimelineLoaded: "불러온 타임라인이 없습니다.",
    statusRequestFailed: "요청이 실패했습니다. 로그를 확인하세요.",
    statusInvalidInput: "입력값이 올바르지 않습니다.",
    statusFieldMustBeNonNegativeInteger: "0 이상의 정수여야 합니다",
    statusFieldRateBetweenZeroAndOne: "0 이상 1 이하 값이어야 합니다",
    statusPreviewLoaded: "프리뷰를 불러왔습니다",
    statusFinalizedPrefix: "확정 완료",
    statusExportedPrefix: "내보내기 완료",
    statusSubmittedPrefix: "제출 완료",
    statusLoadedSubmissionsPrefix: "제출 목록 불러옴",
    statusLoadedAckCatalogPrefix: "ACK 카탈로그 불러옴",
    statusAcknowledgedPrefix: "ACK 처리 완료",
    statusResubmittedPrefix: "재제출 완료",
    statusCanceledPrefix: "취소 완료",
    statusReopenedPrefix: "재오픈 완료",
    statusLoadedTimelinePrefix: "타임라인 불러옴",
    statusAddedEvidencePrefix: "증빙 메모 추가 완료",
    statusAckSubmissionIdRequired: "ACK 제출 ID가 필요합니다",
    statusResubmitSubmissionIdRequired: "재제출 제출 ID가 필요합니다",
    statusCancelSubmissionIdRequired: "취소 제출 ID가 필요합니다",
    statusReopenSubmissionIdRequired: "재오픈 제출 ID가 필요합니다",
    statusTimelineSubmissionIdRequired: "타임라인 제출 ID가 필요합니다",
    statusTimelineSubmissionIdRequiredForEvidence: "증빙 메모에는 타임라인 제출 ID가 필요합니다",
    pendingFinalizationApply: "연말정산 확정 적용",
    pendingFinalizationPreview: "연말정산 확정 프리뷰",
    pendingFilingExport: "연말정산 신고 데이터 내보내기",
    pendingSubmitPackage: "연말정산 신고 패키지 제출",
    pendingListSubmissions: "연말정산 신고 제출 목록 조회",
    pendingAckCatalog: "연말정산 ACK 카탈로그 조회",
    pendingAckSubmission: "연말정산 신고 ACK 처리",
    pendingResubmitSubmission: "연말정산 신고 재제출",
    pendingCancelSubmission: "연말정산 신고 취소",
    pendingReopenSubmission: "연말정산 신고 재오픈",
    pendingLoadTimeline: "연말정산 신고 타임라인 조회",
    pendingAddEvidence: "연말정산 신고 증빙 메모 추가",
    logFinalizeSettlement: "정산 확정",
    logPreviewFinalization: "정산 프리뷰",
    logExportFilingData: "신고 데이터 내보내기",
    logSubmitFilingPackage: "신고 패키지 제출",
    logListFilingSubmissions: "신고 제출 목록 조회",
    logListAckCatalog: "ACK 카탈로그 조회",
    logAcknowledgeSubmission: "신고 ACK 처리",
    logResubmitSubmission: "신고 재제출",
    logCancelSubmission: "신고 취소",
    logReopenSubmission: "신고 재오픈",
    logListSubmissionTimeline: "신고 타임라인 조회",
    logAddEvidenceNote: "증빙 메모 추가",
    yesLabel: "예",
    noLabel: "아니오",
    okLabel: "성공",
    failLabel: "실패",
    readyLabel: "준비됨",
    transportShortManualLabel: "수동",
    transportShortHometaxLabel: "홈택스",
    transportShortNtsApiMockLabel: "국세청-모의",
    submissionTransportOptionLabels: {
      manual_portal: "수동 포털",
      hometax_upload: "홈택스 업로드",
      nts_api_mock: "국세청 API 모의",
      all: "전체"
    },
    exportFormatOptionLabels: {
      json: "JSON",
      csv: "CSV",
      jsonl: "JSONL",
      hometax_csv: "홈택스 CSV"
    },
    validationModeOptionLabels: {
      basic: "기본",
      strict: "엄격"
    },
    submissionStatusOptionLabels: {
      all: "전체",
      submitted: "제출됨",
      acknowledged: "ACK 처리됨",
      canceled: "취소됨"
    },
    ackStatusOptionLabels: {
      all: "전체",
      accepted: "승인",
      rejected: "반려",
      none: "없음"
    },
    validationStatusOptionLabels: {
      all: "전체",
      pass: "통과",
      fail: "실패"
    },
    submissionSortByOptionLabels: {
      submittedAt: "제출 시각",
      attempt: "시도 횟수",
      status: "상태",
      ackStatus: "ACK 상태",
      validationStatus: "검증 상태",
      transport: "전송 방식"
    },
    submissionSortDirectionOptionLabels: {
      desc: "내림차순",
      asc: "오름차순"
    },
    submissionStatusBadgeLabels: {
      submitted: "제출됨",
      acknowledged: "ACK 처리",
      canceled: "취소됨"
    },
    timelineActionBadgeLabels: {
      submitted: "제출됨",
      resubmitted: "재제출됨",
      acknowledged: "승인 확인됨",
      canceled: "취소됨",
      reopened: "재오픈됨",
      evidence_note_added: "증빙 메모 추가"
    },
    timelineAttemptLabel: "시도",
    timelineFromLabel: "원본",
    timelineReasonLabel: "사유",
    timelineNoteLabel: "메모",
    timelineAckPrefix: "ACK",
    timelineReasonCodeLabel: "사유코드",
    timelineDetailLabel: "상세",
    timelineCanceledLabel: "제출 취소됨",
    timelineReopenedLabel: "제출 재오픈됨",
    timelineEvidencePrefix: "증빙 메모"
  },
  en: filingCopyEn
};
