openapi: 3.1.0
info:
  title: FlowHR Attendance API
  version: 1.3.0
paths:
  /attendance/records:
    get:
      summary: List attendance records by period
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: employeeId
          required: false
          schema:
            type: string
        - in: query
          name: state
          required: false
          schema:
            type: string
            enum: [PENDING, APPROVED, REJECTED]
      responses:
        "200":
          description: Records listed
    post:
      summary: Create attendance record
      responses:
        "201":
          description: Created
  /attendance/records/{recordId}:
    patch:
      summary: Update attendance record before approval
      parameters:
        - in: path
          name: recordId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Updated
  /attendance/records/{recordId}/approve:
    post:
      summary: Approve attendance record or correction
      parameters:
        - in: path
          name: recordId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Approved
  /attendance/records/{recordId}/reject:
    post:
      summary: Reject attendance record or correction (optional reason)
      description: 'Optional JSON body `{"reason": string}` can be provided for audit/event trace.'
      parameters:
        - in: path
          name: recordId
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                reason:
                  type: string
                  minLength: 1
                  maxLength: 500
      responses:
        "200":
          description: Rejected
        "400":
          description: Invalid JSON body or invalid payload
