openapi: 3.1.0
info:
  title: FlowHR Payroll API
  version: 1.5.1
paths:
  /payroll/runs:
    get:
      summary: List payroll runs by period
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: employeeId
          required: false
          schema:
            type: string
        - in: query
          name: state
          required: false
          schema:
            type: string
            enum: [PREVIEWED, CONFIRMED]
      responses:
        "200":
          description: Runs listed
  /payroll/deduction-profiles:
    get:
      summary: List deduction profiles
      parameters:
        - in: query
          name: active
          required: false
          schema:
            type: boolean
        - in: query
          name: mode
          required: false
          schema:
            type: string
            enum: [manual, profile]
      responses:
        "200":
          description: Profiles listed
  /payroll/runs/preview:
    post:
      summary: Create payroll gross pay preview
      responses:
        "200":
          description: Preview generated
  /payroll/runs/preview-with-deductions:
    post:
      summary: Create payroll preview with deduction and tax components (manual/profile mode)
      description: In profile mode, `expectedProfileVersion` can be provided to reject stale profile usage with `409`.
      responses:
        "200":
          description: Deduction preview generated
  /payroll/runs/{runId}/confirm:
    post:
      summary: Confirm payroll run
      parameters:
        - in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Payroll run confirmed
  /payroll/deduction-profiles/{profileId}:
    get:
      summary: Read deduction profile
      parameters:
        - in: path
          name: profileId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deduction profile returned
    put:
      summary: Create or update deduction profile
      parameters:
        - in: path
          name: profileId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deduction profile upserted
