openapi: 3.1.0
info:
  title: FlowHR Payroll API
  version: 1.1.0
paths:
  /payroll/runs/preview:
    post:
      summary: Create payroll gross pay preview
      responses:
        "200":
          description: Preview generated
  /payroll/runs/preview-with-deductions:
    post:
      summary: Create payroll preview with deduction and tax components (phase2)
      responses:
        "200":
          description: Deduction preview generated
  /payroll/runs/{runId}/confirm:
    post:
      summary: Confirm payroll run
      parameters:
        - in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Payroll run confirmed
