openapi: 3.1.0
info:
  title: FlowHR Scheduling API
  version: 0.1.0
paths:
  /scheduling/schedules:
    get:
      summary: List schedules
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
        - in: query
          name: to
          required: true
          schema:
            type: string
        - in: query
          name: employeeId
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Schedules listed
        "400":
          description: Invalid query
        "401":
          description: Missing/invalid actor context
        "403":
          description: Insufficient permissions
    post:
      summary: Create schedule
      responses:
        "201":
          description: Created
        "400":
          description: Invalid payload
        "401":
          description: Missing/invalid actor context
        "403":
          description: Insufficient permissions

