ALTER TABLE "Organization"
ADD COLUMN "fiscalYearStart" TEXT NOT NULL DEFAULT '01-01',
ADD COLUMN "workHoursPerDay" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN "overtimeThreshold" DOUBLE PRECISION NOT NULL DEFAULT 8;
